---
- name: Enable fix_pathinfo
  lineinfile: dest=/etc/php5/fpm/php.ini regexp="^;cgi.fix_pathinfo=1" line="cgi.fix_pathinfo=1"

- name: Set max Exec time for PHP
  lineinfile: dest=/etc/php5/fpm/php.ini regexp="^max_execution_time = 30" line="max_execution_time = 3600"

- name: Set memory_limit for php
  lineinfile: dest=/etc/php5/fpm/php.ini regexp="^memory_limit = 128M" line="memory_limit = 750M"

- name: Set session name
  lineinfile: dest=/etc/php5/fpm/php.ini regexp="^session.name = PHPSESSID" line="session.name = PHALSESSID"

- name: Set session lifetime
  lineinfile: dest=/etc/php5/fpm/php.ini regexp="^session.gc_maxlifetime" line="session.gc_maxlifetime = 28800"

- name: Add Phalcon extention to php
  lineinfile: dest=/etc/php5/mods-available/phalcon.ini line="extension=phalcon.so" state=present create=yes

- name: Set FastCGI to TCP
  lineinfile: dest=/etc/php5/fpm/pool.d/www.conf regexp="^listen = /var/run/php5-fpm.sock" line="listen = 127.0.0.1:9000"

- name: Set FastCGI request timeout
  lineinfile: dest=/etc/php5/fpm/pool.d/www.conf regexp="^;request_terminate_timeout = 0" line="request_terminate_timeout = 0"

- name: Enable Phalcon mod
  shell: php5enmod phalcon

- name: Copy Nginx config
  copy: src=default dest=/etc/nginx/sites-available/default

- name: Restart services
  service: name={{ item }} state=restarted
  with_items:
  - nginx
  - php5-fpm
