---
- name: Install apt packages
  apt: pkg={{ item }} state=latest update_cache=yes
  with_items:
  - gcc
  - make
  - git
  - libpcre3-dev
  - nginx
  - php5-fpm
  - php5-dev
  - php5-curl
  - php5-mysql

- name: Clone Phalcon
  git: repo=git://github.com/phalcon/cphalcon.git dest=/tmp/phalcon_repo depth=1 accept_hostkey=yes

- name: Install Phalcon
  shell: cd /tmp/phalcon_repo/build && ./install
